# View examples and documentation at https://deliverybot.dev/docs/
production1:
  environment: production1
  production_environment: true
  payload: {"env": "prod1"}
production2:
  environment: production2
  production_environment: true
  payload: {"env": "prod2"}
staging1:
  environment: staging1
  production_environment: false
  payload: {"env": "staging1"}
staging2:
  environment: staging2
  production_environment: false
  payload: {"env": "staging2"}
integration1:
  environment: integration1
  production_environment: false
  payload: {"env": "integration1"}
integration2:
  environment: integration2
  production_environment: false
  payload: {"env": "integration2"}
